swagger: '2.0'
info:
  version: 1.0.0
  title: Spring Webflux Kotlin Application
  license:
    name: APL2
basePath: /
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  /person:
    get:
      tags:
      - Person
      description: Get all person
      responses:
        '200':
          description: Returns all person
    post:
      tags:
      - Person
      description: Add Person
      parameters:
      - name: person
        description: person name
        in: body
        required: true
        schema:
          $ref: '#/definitions/Person'
      responses:
        '200':
          description: Echo the request inputs
  /person/{id}:
    get:
      tags:
      - Person
      description: Get one person
      responses:
        '200':
          description: Returns one person
    put:
      tags:
      - Person
      description: Update Person
      parameters:
      - name: person
        description: person name
        in: body
        required: true
        schema:
          $ref: '#/definitions/Person'
      responses:
        '200':
          description: Echo the request inputs
    delete:
      tags:
      - Person
      description: Delete one person
      responses:
        '200':
          description: Returns nothing
definitions:
  Person:
    required:
    - id
    - firstName
    - lastName
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      birthdate:
        type: string
        format: date
    example:
      id: 1
      firstName: "John"
      lastName: "Doe"
      birthdate: "2018-11-22"
